Your identification has been saved in /home/xix-sun/.ssh/id_ed25519
Your public key has been saved in /home/xix-sun/.ssh/id_ed25519.pub
The key fingerprint is:
SHA256:q6ZCyg3pEY94+SguxNWOdy6jYO9A5hQlt57zvfzwbOM xix-sun@inland-empire
The key's randomart image is:
+--[ED25519 256]--+
| . o             |
|  + .            |
| . ..            |
| .o...           |
|o+*=o   S        |
|*B+ooo.. .       |
|+O+o..oo.        |
|=o*..ooo=o       |
|oo.=oo+o+E.      |
+----[SHA256]-----+

Your identification has been saved in /home/i-magi/.ssh/id_ed25519
Your public key has been saved in /home/i-magi/.ssh/id_ed25519.pub
The key fingerprint is:
SHA256:SUAtQJhNoHG8Py1WpVeadJ/VUmavwS3+oB6RVlGuq5w i-magi@evil-ball
The key's randomart image is:
+--[ED25519 256]--+
|..oB+oo.      .+=|
| ++ . ..+ o  .o*o|
|.  .   =.= . o=.+|
|  .   o.+.  o+ = |
|   . o .S   + =  |
|    = .    . o + |
|   . o      o . .|
|           o +   |
|            E    |
+----[SHA256]-----+
